title: 'SE for super heroes: an AI approach'
logo: /assets/img/spider.png
google_analytics:
description: ''
remote_theme: mmistakes/minimal-mistakes  
minimal_mistakes_skin: "dark" #$"default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
